# Generated by Django 3.1.2 on 2020-10-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_detectsfaceandcorruptmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectsfaceandcorruptmodel',
            name='targetName',
        ),
        migrations.AddField(
            model_name='detectsfaceandcorruptmodel',
            name='corruptFactor',
            field=models.IntegerField(default=8, null=True),
        ),
    ]
